export interface ProcedureData {
  name: string;
  value: number;
}

export const proceduresByDoctor: Record<string, ProcedureData[]> = {
  'dr-filipe': [
    { name: 'Mastopexia com Protese', value: 0 },
    { name: 'Mastopexia', value: 8000 },
    { name: 'Silicone', value: 10000 },
    { name: 'Face', value: 12000 },
    { name: 'Blefaro', value: 4000 },
    { name: 'Rino ou Ginecomastia', value: 8000 },
    { name: 'Lipo com alta no mesmo dia', value: 6000 },
    { name: 'Lipo com pernoite', value: 6500 },
    { name: 'Abdominoplastia', value: 8000 },
    { name: 'IMPLANTE CAPILAR', value: 0 },
    { name: 'Combinada com protese sem Pernoite (protese de mama +nariz ou lipo )', value: 0 },
    { name: 'Combinada sem  protese sem Pernoite (rino + lipo)', value: 0 },
    { name: 'Combinada sem protese com Pernoite (mama reducao c abdomen//face c nariz)', value: 2178 },
    { name: 'Combinada com protese com Pernoite (mama c protese + Abdomen)', value: 0 },
    { name: 'pequena cirurgia ( retirada de pintas)', value: 0 },
    { name: 'retoque', value: 0 },
    { name: 'CIRURGIA UNIMED', value: 0 },
    { name: 'protese de coxa /ou panturrilha', value: 5000 },
    { name: 'protese glutea', value: 8000 },
    { name: 'Otoplastia sem sedacao', value: 4000 },
    { name: 'contorno corporal (lift de coxa, dorso, braco)', value: 0 },
    { name: 'BICHECTOMIA', value: 1000 },
    { name: 'consulta', value: 100 },
    { name: 'cirugia plástica pequena com sedação', value: 0 },
    { name: 'Morpheus', value: 0 }
  ],
  'dr-vinicius': [
    { name: 'Mastopexia com Protese', value: 0 },
    { name: 'Mastopexia', value: 8000 },
    { name: 'Silicone', value: 10000 },
    { name: 'Face', value: 12000 },
    { name: 'Blefaro', value: 4000 },
    { name: 'Rino ou Ginecomastia', value: 8000 },
    { name: 'Lipo com alta no mesmo dia', value: 6000 },
    { name: 'Lipo com pernoite', value: 6500 },
    { name: 'Abdominoplastia', value: 8000 },
    { name: 'IMPLANTE CAPILAR', value: 0 },
    { name: 'Combinada com protese sem Pernoite (protese de mama +nariz ou lipo )', value: 0 },
    { name: 'Combinada sem  protese sem Pernoite (rino + lipo)', value: 0 },
    { name: 'Combinada sem protese com Pernoite (mama reducao c abdomen//face c nariz)', value: 2178 },
    { name: 'Combinada com protese com Pernoite (mama c protese + Abdomen)', value: 0 },
    { name: 'pequena cirurgia ( retirada de pintas)', value: 0 },
    { name: 'retoque', value: 0 },
    { name: 'CIRURGIA UNIMED', value: 0 },
    { name: 'protese de coxa /ou panturrilha', value: 5000 },
    { name: 'protese glutea', value: 8000 },
    { name: 'Otoplastia sem sedacao', value: 4000 },
    { name: 'contorno corporal (lift de coxa, dorso, braco)', value: 0 },
    { name: 'BICHECTOMIA', value: 1000 },
    { name: 'consulta', value: 100 },
    { name: 'cirugia plástica pequena com sedação', value: 0 }
  ],
  'dr-basile': [
    { name: 'Mastopexia com Protese', value: 0 },
    { name: 'Mastopexia', value: 8000 },
    { name: 'Silicone', value: 10000 },
    { name: 'Face', value: 12000 },
    { name: 'Blefaro', value: 4000 },
    { name: 'Rino ou Ginecomastia', value: 8000 },
    { name: 'Lipo com alta no mesmo dia', value: 6000 },
    { name: 'Lipo com pernoite', value: 6500 },
    { name: 'Abdominoplastia', value: 8000 },
    { name: 'IMPLANTE CAPILAR', value: 0 },
    { name: 'Combinada com protese sem Pernoite (protese de mama +nariz ou lipo )', value: 0 },
    { name: 'Combinada sem  protese sem Pernoite (rino + lipo)', value: 0 },
    { name: 'Combinada sem protese com Pernoite (mama reducao c abdomen//face c nariz)', value: 2178 },
    { name: 'Combinada com protese com Pernoite (mama c protese + Abdomen)', value: 0 },
    { name: 'pequena cirurgia ( retirada de pintas)', value: 0 },
    { name: 'retoque', value: 0 },
    { name: 'CIRURGIA UNIMED', value: 0 },
    { name: 'protese de coxa /ou panturrilha', value: 5000 },
    { name: 'protese glutea', value: 8000 },
    { name: 'Otoplastia sem sedacao', value: 4000 },
    { name: 'contorno corporal (lift de coxa, dorso, braco)', value: 0 },
    { name: 'BICHECTOMIA', value: 1000 },
    { name: 'consulta', value: 100 },
    { name: 'cirugia plástica pequena com sedação', value: 0 }
  ],
  'dr-arthur': [
    { name: 'botox pequeno', value: 0 },
    { name: 'botox médio', value: 0 },
    { name: 'botox axila', value: 0 },
    { name: 'preenchimento', value: 0 },
    { name: 'botox pequeno + preenchimento', value: 0 },
    { name: 'botox médio + preenchimento', value: 0 },
    { name: 'consulta', value: 0 },
    { name: 'limelight', value: 0 },
    { name: 'Pearl fracionado', value: 0 },
    { name: 'Laser cicatriz', value: 0 },
    { name: 'Genesis', value: 0 },
    { name: 'pequena cirurgia', value: 0 },
    { name: 'PCT depilação', value: 0 },
    { name: '1 DEPILAÇÃO', value: 0 },
    { name: 'morpheus rosto', value: 0 },
    { name: 'morpheus palpebra', value: 0 },
    { name: 'morpheus corpo', value: 0 },
    { name: 'biópsia', value: 0 },
    { name: 'EMSCULPTING neo', value: 0 },
    { name: 'radiesse', value: 0 },
    { name: 'voluma', value: 0 },
    { name: 'corticóide', value: 0 },
    { name: 'peeling', value: 0 },
    { name: 'PACOTE ESTRIA', value: 0 },
    { name: 'LASER CAPILAR', value: 0 },
    { name: 'MORPHEUS 2 AREAS', value: 0 },
    { name: 'pacote peeling', value: 0 },
    { name: 'sedação', value: 0 },
    { name: 'PEARL-ARTHUR', value: 0 },
    { name: 'PEARL-FILIPE', value: 0 },
    { name: 'PEARL- BASILE', value: 0 },
    { name: 'PEARL-VINICIUS', value: 0 },
    { name: 'INFILTRAÇÃO CORTICOIDE', value: 0 },
    { name: 'PIAGLIS-PEQUENO', value: 0 },
    { name: 'PIAGLIS -INTEIRO', value: 0 },
    { name: 'MICROAGULHAMENTO', value: 0 },
    { name: 'INFILTRAÇÃO CABELO', value: 0 },
    { name: 'ULTHERA', value: 0 },
    { name: 'SCULPTRA', value: 0 },
    { name: 'SILHOUETTE', value: 0 },
    { name: 'EXILIS FACE/OLHOS/PESCOÇO', value: 0 },
    { name: 'EXILIS CORPO', value: 0 },
    { name: 'COOLSCUPTING', value: 0 },
    { name: 'ENTONE', value: 0 },
    { name: 'morpheus pescoco', value: 0 }
  ],
  'fisioterapia': [
    { name: 'dlus 4 sessões', value: 0 },
    { name: 'Limpeza de pele', value: 0 },
    { name: 'PACOTE LIMPEZA DE PELE', value: 0 },
    { name: 'dlus 10 sessões', value: 0 },
    { name: 'LP+MDA', value: 0 },
    { name: 'PACOTE LP+MDA', value: 0 },
    { name: 'MDA FACIAL', value: 0 },
    { name: 'MDA+PQ+ESTRIAS P', value: 0 },
    { name: 'MDA+PQ+ESTRIAS M', value: 0 },
    { name: 'MDA+PQ+ESTRIAS G', value: 0 },
    { name: '1 DRENAGEM', value: 0 },
    { name: 'DIFERENÇA PACOTE', value: 0 },
    { name: 'MADAH', value: 0 },
    { name: 'FITA SILICONE', value: 0 }
  ],
  'icb-transplante': [
    { name: 'Transplante Capilar', value: 8000 },
    { name: 'Body Hair', value: 0 }
  ]
};

export const doctorOptions = [
  { value: 'dr-filipe', label: 'Dr. Filipe' },
  { value: 'dr-vinicius', label: 'Dr. Vinícius' },
  { value: 'dr-basile', label: 'Dr. Basile' },
  { value: 'dr-arthur', label: 'Dr. Arthur' },
  { value: 'icb-transplante', label: 'ICB Transplante Capilar' },
  { value: 'fisioterapia', label: 'Fisioterapia' }
];

export const paymentMethodOptions = [
  { value: 'pix', label: 'PIX' },
  { value: 'transferencia', label: 'Transferência' },
  { value: 'cartao_credito', label: 'Cartão de Crédito' },
  { value: 'cartao_debito', label: 'Cartão de Débito' },
  { value: 'dinheiro', label: 'Dinheiro' }
];

export const entryByOptions = [
  { value: 'michelle', label: 'Michelle' },
  { value: 'gisele', label: 'Gisele' }
];

export const installmentOptions = [
  { value: '1', label: '1x à vista' },
  { value: '2', label: '2x' },
  { value: '3', label: '3x' },
  { value: '4', label: '4x' },
  { value: '5', label: '5x' },
  { value: '6', label: '6x' },
  { value: '7', label: '7x' },
  { value: '8', label: '8x' },
  { value: '9', label: '9x' },
  { value: '10', label: '10x' },
  { value: '11', label: '11x' },
  { value: '12', label: '12x' }
];
